tuanle99/Project-2

controllers/api/index.js
controllers/api/userRoutes.js
htmlMockup/homepageMock.html
views/layouts/main.handlebars

Includes html mockup for homepage, along with first views for login, signup, main and home. Also included som einitial routes for rendering home page, login, signup along with the client logic for signup and login within public. 
Lastly, routes were upated wtih comment sectoins as placeholders for our get, post, put delete routes.

updated views, first routes, login, signup, homepage,main

---

db/schema.sql
models/Comment.js
models/Project.js
models/Task.js
models/User.js
models/index.js

Now this has the comment model and corrected relationships in index.js

Model setup sam

---

models/Comment.js
seeds/comment-seeds.js
seeds/finance-seeds.js
seeds/index.js
seeds/project-seeds.js
seeds/task-seeds.js
seeds/user-seeds.js

Updated with seeds for all models so far except finance, as we will wait for charles to present his mockup on the page view.

Model seeds

---

controllers/index.js
public/js/login.js
public/js/logout.js
public/js/signup.js
views/homepage.handlebars
views/login.handlebars
views/signup.handlebars

Updated login and signup should be good for @smcmillan28  to work with on routes. I think the client script for signup is already providing what you need as a json object, just need to make the paths right and such. let me know if you have questions. 
Video demo of signup, and notes are attached
https://user-images.githubusercontent.com/72420733/112773167-f46c3a80-9002-11eb-8c3f-be13114748cd.mp4

Loginsignup style baseroutes

---

controllers/homeRoutes.js
public/js/homepage.js
server.js
views/homepage.handlebars
views/layouts/main.handlebars

https://user-images.githubusercontent.com/72420733/112887277-f84e9a00-90a0-11eb-9a20-c8df9cd40e27.mp4

Homepage client script create task and related updates (notes and vid attached)

---

controllers/api/index.js
htmlMockup/homepageMock.html
models/finance.js
public/js/homepage.js
seeds/task-seeds.js
views/homepage.handlebars

notes and video below what I did and what I changed
https://user-images.githubusercontent.com/72420733/112902875-c9422380-90b4-11eb-97cb-5e90a3dcf4fb.mp4

Task completed client logic

---

controllers/api/userRoutes.js
controllers/homeRoutes.js
models/User.js
public/js/logout.js
public/js/signup.js
views/layouts/main.handlebars

- Conditionally added logout script to main.handlebars if user is logged_in
- Conditionally handled navbar links in main.handlebars if user is logged_in
- Users can signup from the login page, adding their info to the database
- Users can logout, killing their session
- Some user data has been made nullable (birthday, is_admin)
- I figure birthday can be incorporated in future development post MVP
- is_admin functionality can potentially be handled using "role" attribute (will discuss Tuesday 3/30)

Signup login routing sam

---

controllers/homeRoutes.js
htmlMockup/financeTest.html
models/finance.js
models/index.js
package.json
seeds/finance-seeds.js
seeds/index.js
views/finance.handlebars

Hi guys. Please approve my request. I have the finance part. I also updated some of the files that you created.

Updating all files to update finance information

---

controllers/api/budgetRoutes.js
controllers/api/index.js
models/Budget.js
models/index.js
seeds/budget-seeds.js
seeds/index.js
views/budget.handlebars
views/layouts/main.handlebars

budget page still needs updated styling, charles will work on this

edited navbar order of links, added budget model and budget route

---

controllers/homeRoutes.js
public/js/homepage.js
views/homepage.handlebars

Did a quick smoke test all stuff still working in areas I changed. Also signup worked good for me- looks great first time I've seen it with new nav. Notes of changes, things missing I need to circle back to and demo below. Thanks!
https://user-images.githubusercontent.com/72420733/113078325-db998b80-91a0-11eb-9083-6cfb0b91eea6.mp4

Comments functionality

---

controllers/api/commentRoutes.js
controllers/api/index.js
controllers/api/taskRoutes.js
models/Task.js
public/js/homepage.js

User can post, update, delete tasks on homepage once logged in:
- Added tasksRoutes and commentRoutes to api routes folder
- Added "is_complete" variable to homepage.js for status update functionality
- Once logged in, user can add a new task, update a task details, delete a task

Homepage Task Routes Completed

---

controllers/homeRoutes.js

Sorts by date on homepage. @tuanle99  will need to add the same order clause in where he provides data to project or my tasks. Its just one line so pretty crisp. 
https://user-images.githubusercontent.com/72420733/113153557-3795fb80-9205-11eb-9574-cff77790c02d.mp4

Sort task by date

---

controllers/api/commentRoutes.js
public/js/homepage.js

- Once logged in, user can create, update, delete tasks
- Tasks are sorting by due date (logic included by Ryan)
- Once logged in, user can comment on tasks
- Comments still show user_id as commentor and not user name

Comment Routes Working

---

controllers/homeRoutes.js
public/js/homepage.js
views/homepage.handlebars

https://user-images.githubusercontent.com/72420733/113203758-6da1a280-923a-11eb-8371-1bf121ae7b9a.mp4

Task date visulization improvements

---

public/js/homepage.js

https://user-images.githubusercontent.com/72420733/113217882-8f0b8a00-924c-11eb-8e87-b6721921dfa1.mp4

Task date validation

---

README.md
public/js/budget.js
views/budget.handlebars

I and Sam updated the front end html and JavaScript for the budget page. Still need to work on the update budget.

We updated the finance files

---

controllers/api/budgetRoutes.js
public/js/budget.js
views/budget.handlebars

Post and delete routes working for Finance page.

Backend budget routes

---

views/budget.handlebars

handlebars didn't update from last merge

Budget page fix sam

---

controllers/api/projectRoutes.js
public/js/homepage.js
public/js/newTask.js
views/project.handlebars

https://user-images.githubusercontent.com/72420733/113376390-9d869e00-933f-11eb-9bf6-f9561ad94e0e.mp4

button for new task in project

---

controllers/api/profileRoutes.js
controllers/api/projectRoutes.js
controllers/homeRoutes.js
public/js/homepage.js
public/js/newTask_profile.js
public/js/taskSortFormat.js
views/profile.handlebars
views/project.handlebars

https://user-images.githubusercontent.com/72420733/113429631-d86fec80-93a6-11eb-937b-c3f3d46a4505.mp4

Task row updates project profile

---

controllers/api/budgetRoutes.js
controllers/api/profileRoutes.js
controllers/api/projectRoutes.js
controllers/api/userRoutes.js
controllers/homeRoutes.js
public/js/homepage.js
views/homepage.handlebars
views/layouts/main.handlebars
views/profile.handlebars
views/project.handlebars

https://user-images.githubusercontent.com/72420733/113435923-c21b5e00-93b1-11eb-8182-f2f74daf6008.mp4

Navbar fixes activestate

---

README.md

Hi guys. I finished the README file. Please approve it!

I finished the README file
